import { type OptionsResponse } from "../Models/Option";

export const optionsResponse: OptionsResponse = {
  results: [
    // ---- CALLS ----
    {
      day: {
        change: 1.25,
        change_percent: 0.03,
        close: 5.6,
        high: 6.0,
        last_updated: Date.now(),
        low: 5.4,
        open: 5.5,
        previous_close: 5.35,
        volume: 1200,
        vwap: 5.55,
      },
      details: {
        contract_type: "call",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 100,
        ticker: "OPT-C-100-20251017",
      },
      greeks: { delta: 0.55, gamma: 0.04, theta: -0.02, vega: 0.12 },
      implied_volatility: 0.25,
      open_interest: 500,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: 0.75,
        change_percent: 0.02,
        close: 7.1,
        high: 7.5,
        last_updated: Date.now(),
        low: 6.9,
        open: 7.0,
        previous_close: 6.8,
        volume: 950,
        vwap: 7.2,
      },
      details: {
        contract_type: "call",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 105,
        ticker: "OPT-C-105-20251121",
      },
      greeks: { delta: 0.48, gamma: 0.05, theta: -0.03, vega: 0.15 },
      implied_volatility: 0.28,
      open_interest: 600,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: 1.1,
        change_percent: 0.025,
        close: 6.3,
        high: 6.7,
        last_updated: Date.now(),
        low: 6.0,
        open: 6.2,
        previous_close: 6.19,
        volume: 1020,
        vwap: 6.4,
      },
      details: {
        contract_type: "call",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 110,
        ticker: "OPT-C-110-20251219",
      },
      greeks: { delta: 0.51, gamma: 0.045, theta: -0.025, vega: 0.14 },
      implied_volatility: 0.26,
      open_interest: 450,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: 0.9,
        change_percent: 0.018,
        close: 8.2,
        high: 8.5,
        last_updated: Date.now(),
        low: 8.0,
        open: 8.1,
        previous_close: 8.0,
        volume: 880,
        vwap: 8.3,
      },
      details: {
        contract_type: "call",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 115,
        ticker: "OPT-C-115-20260116",
      },
      greeks: { delta: 0.46, gamma: 0.052, theta: -0.031, vega: 0.16 },
      implied_volatility: 0.3,
      open_interest: 700,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: 1.35,
        change_percent: 0.027,
        close: 9.0,
        high: 9.4,
        last_updated: Date.now(),
        low: 8.8,
        open: 8.9,
        previous_close: 8.7,
        volume: 1300,
        vwap: 9.1,
      },
      details: {
        contract_type: "call",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 120,
        ticker: "OPT-C-120-20260220",
      },
      greeks: { delta: 0.49, gamma: 0.048, theta: -0.029, vega: 0.18 },
      implied_volatility: 0.29,
      open_interest: 650,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: 0.65,
        change_percent: 0.012,
        close: 4.9,
        high: 5.1,
        last_updated: Date.now(),
        low: 4.7,
        open: 4.8,
        previous_close: 4.8,
        volume: 720,
        vwap: 4.95,
      },
      details: {
        contract_type: "call",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 125,
        ticker: "OPT-C-125-20260320",
      },
      greeks: { delta: 0.41, gamma: 0.037, theta: -0.035, vega: 0.19 },
      implied_volatility: 0.32,
      open_interest: 580,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: 1.0,
        change_percent: 0.02,
        close: 6.8,
        high: 7.0,
        last_updated: Date.now(),
        low: 6.6,
        open: 6.7,
        previous_close: 6.6,
        volume: 890,
        vwap: 6.85,
      },
      details: {
        contract_type: "call",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 130,
        ticker: "OPT-C-130-20260417",
      },
      greeks: { delta: 0.43, gamma: 0.042, theta: -0.028, vega: 0.2 },
      implied_volatility: 0.31,
      open_interest: 720,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: 0.8,
        change_percent: 0.017,
        close: 7.5,
        high: 7.8,
        last_updated: Date.now(),
        low: 7.3,
        open: 7.4,
        previous_close: 7.2,
        volume: 940,
        vwap: 7.6,
      },
      details: {
        contract_type: "call",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 135,
        ticker: "OPT-C-135-20260515",
      },
      greeks: { delta: 0.45, gamma: 0.044, theta: -0.027, vega: 0.21 },
      implied_volatility: 0.3,
      open_interest: 690,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: 1.2,
        change_percent: 0.023,
        close: 8.6,
        high: 8.9,
        last_updated: Date.now(),
        low: 8.3,
        open: 8.4,
        previous_close: 8.4,
        volume: 1100,
        vwap: 8.7,
      },
      details: {
        contract_type: "call",
        exercise_style: "american",
        expiration_date: "2026-06-19",
        shares_per_contract: 100,
        strike_price: 140,
        ticker: "OPT-C-140-20260619",
      },
      greeks: { delta: 0.47, gamma: 0.046, theta: -0.026, vega: 0.22 },
      implied_volatility: 0.29,
      open_interest: 710,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: 0.95,
        change_percent: 0.019,
        close: 9.4,
        high: 9.7,
        last_updated: Date.now(),
        low: 9.1,
        open: 9.2,
        previous_close: 9.0,
        volume: 1250,
        vwap: 9.5,
      },
      details: {
        contract_type: "call",
        exercise_style: "american",
        expiration_date: "2026-07-17",
        shares_per_contract: 100,
        strike_price: 145,
        ticker: "OPT-C-145-20260717",
      },
      greeks: { delta: 0.5, gamma: 0.047, theta: -0.024, vega: 0.23 },
      implied_volatility: 0.28,
      open_interest: 730,
      underlying_asset: { ticker: "SPY" },
    },

    // ---- PUTS ----
    {
      day: {
        change: -0.5,
        change_percent: -0.01,
        close: 4.3,
        high: 4.6,
        last_updated: Date.now(),
        low: 4.2,
        open: 4.4,
        previous_close: 4.8,
        volume: 1100,
        vwap: 4.35,
      },
      details: {
        contract_type: "put",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 100,
        ticker: "OPT-P-100-20251017",
      },
      greeks: { delta: -0.45, gamma: 0.03, theta: -0.04, vega: 0.13 },
      implied_volatility: 0.27,
      open_interest: 550,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: -0.3,
        change_percent: -0.02,
        close: 5.0,
        high: 5.3,
        last_updated: Date.now(),
        low: 4.9,
        open: 5.2,
        previous_close: 5.1,
        volume: 870,
        vwap: 5.05,
      },
      details: {
        contract_type: "put",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 105,
        ticker: "OPT-P-105-20251121",
      },
      greeks: { delta: -0.52, gamma: 0.04, theta: -0.05, vega: 0.17 },
      implied_volatility: 0.31,
      open_interest: 480,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: -0.6,
        change_percent: -0.015,
        close: 6.1,
        high: 6.4,
        last_updated: Date.now(),
        low: 5.9,
        open: 6.2,
        previous_close: 6.3,
        volume: 920,
        vwap: 6.15,
      },
      details: {
        contract_type: "put",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 110,
        ticker: "OPT-P-110-20251219",
      },
      greeks: { delta: -0.49, gamma: 0.035, theta: -0.045, vega: 0.16 },
      implied_volatility: 0.29,
      open_interest: 520,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: -0.4,
        change_percent: -0.01,
        close: 7.2,
        high: 7.6,
        last_updated: Date.now(),
        low: 7.0,
        open: 7.3,
        previous_close: 7.4,
        volume: 850,
        vwap: 7.3,
      },
      details: {
        contract_type: "put",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 115,
        ticker: "OPT-P-115-20260116",
      },
      greeks: { delta: -0.51, gamma: 0.038, theta: -0.043, vega: 0.18 },
      implied_volatility: 0.3,
      open_interest: 600,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: -0.7,
        change_percent: -0.017,
        close: 8.4,
        high: 8.7,
        last_updated: Date.now(),
        low: 8.1,
        open: 8.3,
        previous_close: 8.5,
        volume: 970,
        vwap: 8.35,
      },
      details: {
        contract_type: "put",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 120,
        ticker: "OPT-P-120-20260220",
      },
      greeks: { delta: -0.53, gamma: 0.039, theta: -0.046, vega: 0.19 },
      implied_volatility: 0.32,
      open_interest: 640,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: -0.55,
        change_percent: -0.012,
        close: 5.7,
        high: 5.9,
        last_updated: Date.now(),
        low: 5.5,
        open: 5.6,
        previous_close: 5.8,
        volume: 790,
        vwap: 5.75,
      },
      details: {
        contract_type: "put",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 125,
        ticker: "OPT-P-125-20260320",
      },
      greeks: { delta: -0.47, gamma: 0.034, theta: -0.044, vega: 0.17 },
      implied_volatility: 0.28,
      open_interest: 500,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: -0.45,
        change_percent: -0.01,
        close: 6.5,
        high: 6.8,
        last_updated: Date.now(),
        low: 6.3,
        open: 6.4,
        previous_close: 6.7,
        volume: 860,
        vwap: 6.6,
      },
      details: {
        contract_type: "put",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 130,
        ticker: "OPT-P-130-20260417",
      },
      greeks: { delta: -0.5, gamma: 0.036, theta: -0.042, vega: 0.18 },
      implied_volatility: 0.29,
      open_interest: 570,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: -0.65,
        change_percent: -0.013,
        close: 7.8,
        high: 8.0,
        last_updated: Date.now(),
        low: 7.6,
        open: 7.7,
        previous_close: 7.9,
        volume: 910,
        vwap: 7.85,
      },
      details: {
        contract_type: "put",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 135,
        ticker: "OPT-P-135-20260515",
      },
      greeks: { delta: -0.52, gamma: 0.037, theta: -0.041, vega: 0.19 },
      implied_volatility: 0.31,
      open_interest: 620,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: -0.5,
        change_percent: -0.011,
        close: 8.9,
        high: 9.2,
        last_updated: Date.now(),
        low: 8.6,
        open: 8.8,
        previous_close: 9.0,
        volume: 1040,
        vwap: 8.95,
      },
      details: {
        contract_type: "put",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 140,
        ticker: "OPT-P-140-20260619",
      },
      greeks: { delta: -0.54, gamma: 0.038, theta: -0.04, vega: 0.21 },
      implied_volatility: 0.33,
      open_interest: 660,
      underlying_asset: { ticker: "SPY" },
    },
    {
      day: {
        change: -0.7,
        change_percent: -0.015,
        close: 9.7,
        high: 10.0,
        last_updated: Date.now(),
        low: 9.5,
        open: 9.6,
        previous_close: 9.8,
        volume: 1150,
        vwap: 9.8,
      },
      details: {
        contract_type: "put",
        exercise_style: "american",
        expiration_date: "2025-09-26",
        shares_per_contract: 100,
        strike_price: 145,
        ticker: "OPT-P-145-20260717",
      },
      greeks: { delta: -0.56, gamma: 0.039, theta: -0.039, vega: 0.22 },
      implied_volatility: 0.34,
      open_interest: 690,
      underlying_asset: { ticker: "SPY" },
    },
  ],
  status: "OK",
  request_id: "stub-req-12345",
  next_url: "/options?page=2",
};
